# Generated by Django 4.0.2 on 2022-03-22 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rater', '0002_module_remove_modules_module_code_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Modules',
            new_name='ModuleInstances',
        ),
    ]
